// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_qos.proto

#include "control_qos.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR QosControl::QosControl(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.drb_qos_)*/{}
  , /*decltype(_impl_.ran_index_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct QosControlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QosControlDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QosControlDefaultTypeInternal() {}
  union {
    QosControl _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QosControlDefaultTypeInternal _QosControl_default_instance_;
PROTOBUF_CONSTEXPR DrbQosParams::DrbQosParams(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.rnti_)*/0u
  , /*decltype(_impl_.lcid_)*/0u
  , /*decltype(_impl_.qos_priority_)*/0u
  , /*decltype(_impl_.arp_priority_)*/0u
  , /*decltype(_impl_.gbr_dl_)*/uint64_t{0u}
  , /*decltype(_impl_.pdb_ms_)*/0u
  , /*decltype(_impl_.clear_override_)*/false
  , /*decltype(_impl_.gbr_ul_)*/uint64_t{0u}} {}
struct DrbQosParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DrbQosParamsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DrbQosParamsDefaultTypeInternal() {}
  union {
    DrbQosParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DrbQosParamsDefaultTypeInternal _DrbQosParams_default_instance_;
static ::_pb::Metadata file_level_metadata_control_5fqos_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_control_5fqos_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_control_5fqos_2eproto = nullptr;

const uint32_t TableStruct_control_5fqos_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QosControl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QosControl, _impl_.ran_index_),
  PROTOBUF_FIELD_OFFSET(::QosControl, _impl_.drb_qos_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.rnti_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.lcid_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.qos_priority_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.arp_priority_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.pdb_ms_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.gbr_dl_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.gbr_ul_),
  PROTOBUF_FIELD_OFFSET(::DrbQosParams, _impl_.clear_override_),
  ~0u,
  ~0u,
  0,
  1,
  3,
  2,
  4,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::QosControl)},
  { 8, 22, -1, sizeof(::DrbQosParams)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_QosControl_default_instance_._instance,
  &::_DrbQosParams_default_instance_._instance,
};

const char descriptor_table_protodef_control_5fqos_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021control_qos.proto\"\?\n\nQosControl\022\021\n\tran"
  "_index\030\001 \001(\r\022\036\n\007drb_qos\030\002 \003(\0132\r.DrbQosPa"
  "rams\"\372\001\n\014DrbQosParams\022\014\n\004rnti\030\001 \001(\r\022\014\n\004l"
  "cid\030\002 \001(\r\022\031\n\014qos_priority\030\003 \001(\rH\000\210\001\001\022\031\n\014"
  "arp_priority\030\004 \001(\rH\001\210\001\001\022\023\n\006pdb_ms\030\005 \001(\rH"
  "\002\210\001\001\022\023\n\006gbr_dl\030\006 \001(\004H\003\210\001\001\022\023\n\006gbr_ul\030\007 \001("
  "\004H\004\210\001\001\022\026\n\016clear_override\030\010 \001(\010B\017\n\r_qos_p"
  "riorityB\017\n\r_arp_priorityB\t\n\007_pdb_msB\t\n\007_"
  "gbr_dlB\t\n\007_gbr_ulb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_control_5fqos_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_5fqos_2eproto = {
    false, false, 345, descriptor_table_protodef_control_5fqos_2eproto,
    "control_qos.proto",
    &descriptor_table_control_5fqos_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_control_5fqos_2eproto::offsets,
    file_level_metadata_control_5fqos_2eproto, file_level_enum_descriptors_control_5fqos_2eproto,
    file_level_service_descriptors_control_5fqos_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_5fqos_2eproto_getter() {
  return &descriptor_table_control_5fqos_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_5fqos_2eproto(&descriptor_table_control_5fqos_2eproto);

// ===================================================================

class QosControl::_Internal {
 public:
};

QosControl::QosControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QosControl)
}
QosControl::QosControl(const QosControl& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QosControl* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.drb_qos_){from._impl_.drb_qos_}
    , decltype(_impl_.ran_index_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.ran_index_ = from._impl_.ran_index_;
  // @@protoc_insertion_point(copy_constructor:QosControl)
}

inline void QosControl::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.drb_qos_){arena}
    , decltype(_impl_.ran_index_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

QosControl::~QosControl() {
  // @@protoc_insertion_point(destructor:QosControl)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QosControl::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.drb_qos_.~RepeatedPtrField();
}

void QosControl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QosControl::Clear() {
// @@protoc_insertion_point(message_clear_start:QosControl)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.drb_qos_.Clear();
  _impl_.ran_index_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QosControl::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 ran_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ran_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .DrbQosParams drb_qos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_drb_qos(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QosControl::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QosControl)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ran_index = 1;
  if (this->_internal_ran_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ran_index(), target);
  }

  // repeated .DrbQosParams drb_qos = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_drb_qos_size()); i < n; i++) {
    const auto& repfield = this->_internal_drb_qos(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QosControl)
  return target;
}

size_t QosControl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QosControl)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .DrbQosParams drb_qos = 2;
  total_size += 1UL * this->_internal_drb_qos_size();
  for (const auto& msg : this->_impl_.drb_qos_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 ran_index = 1;
  if (this->_internal_ran_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ran_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QosControl::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QosControl::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QosControl::GetClassData() const { return &_class_data_; }


void QosControl::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QosControl*>(&to_msg);
  auto& from = static_cast<const QosControl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QosControl)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.drb_qos_.MergeFrom(from._impl_.drb_qos_);
  if (from._internal_ran_index() != 0) {
    _this->_internal_set_ran_index(from._internal_ran_index());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QosControl::CopyFrom(const QosControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QosControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QosControl::IsInitialized() const {
  return true;
}

void QosControl::InternalSwap(QosControl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.drb_qos_.InternalSwap(&other->_impl_.drb_qos_);
  swap(_impl_.ran_index_, other->_impl_.ran_index_);
}

::PROTOBUF_NAMESPACE_ID::Metadata QosControl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fqos_2eproto_getter, &descriptor_table_control_5fqos_2eproto_once,
      file_level_metadata_control_5fqos_2eproto[0]);
}

// ===================================================================

class DrbQosParams::_Internal {
 public:
  using HasBits = decltype(std::declval<DrbQosParams>()._impl_._has_bits_);
  static void set_has_qos_priority(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_arp_priority(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_pdb_ms(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_gbr_dl(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_gbr_ul(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

DrbQosParams::DrbQosParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DrbQosParams)
}
DrbQosParams::DrbQosParams(const DrbQosParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DrbQosParams* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rnti_){}
    , decltype(_impl_.lcid_){}
    , decltype(_impl_.qos_priority_){}
    , decltype(_impl_.arp_priority_){}
    , decltype(_impl_.gbr_dl_){}
    , decltype(_impl_.pdb_ms_){}
    , decltype(_impl_.clear_override_){}
    , decltype(_impl_.gbr_ul_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.rnti_, &from._impl_.rnti_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.gbr_ul_) -
    reinterpret_cast<char*>(&_impl_.rnti_)) + sizeof(_impl_.gbr_ul_));
  // @@protoc_insertion_point(copy_constructor:DrbQosParams)
}

inline void DrbQosParams::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rnti_){0u}
    , decltype(_impl_.lcid_){0u}
    , decltype(_impl_.qos_priority_){0u}
    , decltype(_impl_.arp_priority_){0u}
    , decltype(_impl_.gbr_dl_){uint64_t{0u}}
    , decltype(_impl_.pdb_ms_){0u}
    , decltype(_impl_.clear_override_){false}
    , decltype(_impl_.gbr_ul_){uint64_t{0u}}
  };
}

DrbQosParams::~DrbQosParams() {
  // @@protoc_insertion_point(destructor:DrbQosParams)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DrbQosParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DrbQosParams::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DrbQosParams::Clear() {
// @@protoc_insertion_point(message_clear_start:DrbQosParams)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.rnti_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lcid_) -
      reinterpret_cast<char*>(&_impl_.rnti_)) + sizeof(_impl_.lcid_));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.qos_priority_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.pdb_ms_) -
        reinterpret_cast<char*>(&_impl_.qos_priority_)) + sizeof(_impl_.pdb_ms_));
  }
  _impl_.clear_override_ = false;
  _impl_.gbr_ul_ = uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DrbQosParams::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 rnti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rnti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 lcid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.lcid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 qos_priority = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_qos_priority(&has_bits);
          _impl_.qos_priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 arp_priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_arp_priority(&has_bits);
          _impl_.arp_priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 pdb_ms = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_pdb_ms(&has_bits);
          _impl_.pdb_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 gbr_dl = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_gbr_dl(&has_bits);
          _impl_.gbr_dl_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 gbr_ul = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_gbr_ul(&has_bits);
          _impl_.gbr_ul_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool clear_override = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.clear_override_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DrbQosParams::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DrbQosParams)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->_internal_rnti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_rnti(), target);
  }

  // uint32 lcid = 2;
  if (this->_internal_lcid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_lcid(), target);
  }

  // optional uint32 qos_priority = 3;
  if (_internal_has_qos_priority()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_qos_priority(), target);
  }

  // optional uint32 arp_priority = 4;
  if (_internal_has_arp_priority()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_arp_priority(), target);
  }

  // optional uint32 pdb_ms = 5;
  if (_internal_has_pdb_ms()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_pdb_ms(), target);
  }

  // optional uint64 gbr_dl = 6;
  if (_internal_has_gbr_dl()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_gbr_dl(), target);
  }

  // optional uint64 gbr_ul = 7;
  if (_internal_has_gbr_ul()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(7, this->_internal_gbr_ul(), target);
  }

  // bool clear_override = 8;
  if (this->_internal_clear_override() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_clear_override(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DrbQosParams)
  return target;
}

size_t DrbQosParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DrbQosParams)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->_internal_rnti() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_rnti());
  }

  // uint32 lcid = 2;
  if (this->_internal_lcid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_lcid());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional uint32 qos_priority = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_qos_priority());
    }

    // optional uint32 arp_priority = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_arp_priority());
    }

    // optional uint64 gbr_dl = 6;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_gbr_dl());
    }

    // optional uint32 pdb_ms = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_pdb_ms());
    }

  }
  // bool clear_override = 8;
  if (this->_internal_clear_override() != 0) {
    total_size += 1 + 1;
  }

  // optional uint64 gbr_ul = 7;
  if (cached_has_bits & 0x00000010u) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_gbr_ul());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DrbQosParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DrbQosParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DrbQosParams::GetClassData() const { return &_class_data_; }


void DrbQosParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DrbQosParams*>(&to_msg);
  auto& from = static_cast<const DrbQosParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DrbQosParams)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_rnti() != 0) {
    _this->_internal_set_rnti(from._internal_rnti());
  }
  if (from._internal_lcid() != 0) {
    _this->_internal_set_lcid(from._internal_lcid());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.qos_priority_ = from._impl_.qos_priority_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.arp_priority_ = from._impl_.arp_priority_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.gbr_dl_ = from._impl_.gbr_dl_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.pdb_ms_ = from._impl_.pdb_ms_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (from._internal_clear_override() != 0) {
    _this->_internal_set_clear_override(from._internal_clear_override());
  }
  if (cached_has_bits & 0x00000010u) {
    _this->_internal_set_gbr_ul(from._internal_gbr_ul());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DrbQosParams::CopyFrom(const DrbQosParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DrbQosParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DrbQosParams::IsInitialized() const {
  return true;
}

void DrbQosParams::InternalSwap(DrbQosParams* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DrbQosParams, _impl_.gbr_ul_)
      + sizeof(DrbQosParams::_impl_.gbr_ul_)
      - PROTOBUF_FIELD_OFFSET(DrbQosParams, _impl_.rnti_)>(
          reinterpret_cast<char*>(&_impl_.rnti_),
          reinterpret_cast<char*>(&other->_impl_.rnti_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DrbQosParams::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fqos_2eproto_getter, &descriptor_table_control_5fqos_2eproto_once,
      file_level_metadata_control_5fqos_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::QosControl*
Arena::CreateMaybeMessage< ::QosControl >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QosControl >(arena);
}
template<> PROTOBUF_NOINLINE ::DrbQosParams*
Arena::CreateMaybeMessage< ::DrbQosParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DrbQosParams >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
