// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_qos.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_5fqos_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_5fqos_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_5fqos_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_5fqos_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_5fqos_2eproto;
class DrbQosParams;
struct DrbQosParamsDefaultTypeInternal;
extern DrbQosParamsDefaultTypeInternal _DrbQosParams_default_instance_;
class QosControl;
struct QosControlDefaultTypeInternal;
extern QosControlDefaultTypeInternal _QosControl_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DrbQosParams* Arena::CreateMaybeMessage<::DrbQosParams>(Arena*);
template<> ::QosControl* Arena::CreateMaybeMessage<::QosControl>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class QosControl final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QosControl) */ {
 public:
  inline QosControl() : QosControl(nullptr) {}
  ~QosControl() override;
  explicit PROTOBUF_CONSTEXPR QosControl(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QosControl(const QosControl& from);
  QosControl(QosControl&& from) noexcept
    : QosControl() {
    *this = ::std::move(from);
  }

  inline QosControl& operator=(const QosControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline QosControl& operator=(QosControl&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QosControl& default_instance() {
    return *internal_default_instance();
  }
  static inline const QosControl* internal_default_instance() {
    return reinterpret_cast<const QosControl*>(
               &_QosControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QosControl& a, QosControl& b) {
    a.Swap(&b);
  }
  inline void Swap(QosControl* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QosControl* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QosControl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QosControl>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QosControl& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QosControl& from) {
    QosControl::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QosControl* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QosControl";
  }
  protected:
  explicit QosControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDrbQosFieldNumber = 2,
    kRanIndexFieldNumber = 1,
  };
  // repeated .DrbQosParams drb_qos = 2;
  int drb_qos_size() const;
  private:
  int _internal_drb_qos_size() const;
  public:
  void clear_drb_qos();
  ::DrbQosParams* mutable_drb_qos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbQosParams >*
      mutable_drb_qos();
  private:
  const ::DrbQosParams& _internal_drb_qos(int index) const;
  ::DrbQosParams* _internal_add_drb_qos();
  public:
  const ::DrbQosParams& drb_qos(int index) const;
  ::DrbQosParams* add_drb_qos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbQosParams >&
      drb_qos() const;

  // uint32 ran_index = 1;
  void clear_ran_index();
  uint32_t ran_index() const;
  void set_ran_index(uint32_t value);
  private:
  uint32_t _internal_ran_index() const;
  void _internal_set_ran_index(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QosControl)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbQosParams > drb_qos_;
    uint32_t ran_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fqos_2eproto;
};
// -------------------------------------------------------------------

class DrbQosParams final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DrbQosParams) */ {
 public:
  inline DrbQosParams() : DrbQosParams(nullptr) {}
  ~DrbQosParams() override;
  explicit PROTOBUF_CONSTEXPR DrbQosParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DrbQosParams(const DrbQosParams& from);
  DrbQosParams(DrbQosParams&& from) noexcept
    : DrbQosParams() {
    *this = ::std::move(from);
  }

  inline DrbQosParams& operator=(const DrbQosParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline DrbQosParams& operator=(DrbQosParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DrbQosParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const DrbQosParams* internal_default_instance() {
    return reinterpret_cast<const DrbQosParams*>(
               &_DrbQosParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DrbQosParams& a, DrbQosParams& b) {
    a.Swap(&b);
  }
  inline void Swap(DrbQosParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DrbQosParams* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DrbQosParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DrbQosParams>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DrbQosParams& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DrbQosParams& from) {
    DrbQosParams::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DrbQosParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DrbQosParams";
  }
  protected:
  explicit DrbQosParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRntiFieldNumber = 1,
    kLcidFieldNumber = 2,
    kQosPriorityFieldNumber = 3,
    kArpPriorityFieldNumber = 4,
    kGbrDlFieldNumber = 6,
    kPdbMsFieldNumber = 5,
    kClearOverrideFieldNumber = 8,
    kGbrUlFieldNumber = 7,
  };
  // uint32 rnti = 1;
  void clear_rnti();
  uint32_t rnti() const;
  void set_rnti(uint32_t value);
  private:
  uint32_t _internal_rnti() const;
  void _internal_set_rnti(uint32_t value);
  public:

  // uint32 lcid = 2;
  void clear_lcid();
  uint32_t lcid() const;
  void set_lcid(uint32_t value);
  private:
  uint32_t _internal_lcid() const;
  void _internal_set_lcid(uint32_t value);
  public:

  // optional uint32 qos_priority = 3;
  bool has_qos_priority() const;
  private:
  bool _internal_has_qos_priority() const;
  public:
  void clear_qos_priority();
  uint32_t qos_priority() const;
  void set_qos_priority(uint32_t value);
  private:
  uint32_t _internal_qos_priority() const;
  void _internal_set_qos_priority(uint32_t value);
  public:

  // optional uint32 arp_priority = 4;
  bool has_arp_priority() const;
  private:
  bool _internal_has_arp_priority() const;
  public:
  void clear_arp_priority();
  uint32_t arp_priority() const;
  void set_arp_priority(uint32_t value);
  private:
  uint32_t _internal_arp_priority() const;
  void _internal_set_arp_priority(uint32_t value);
  public:

  // optional uint64 gbr_dl = 6;
  bool has_gbr_dl() const;
  private:
  bool _internal_has_gbr_dl() const;
  public:
  void clear_gbr_dl();
  uint64_t gbr_dl() const;
  void set_gbr_dl(uint64_t value);
  private:
  uint64_t _internal_gbr_dl() const;
  void _internal_set_gbr_dl(uint64_t value);
  public:

  // optional uint32 pdb_ms = 5;
  bool has_pdb_ms() const;
  private:
  bool _internal_has_pdb_ms() const;
  public:
  void clear_pdb_ms();
  uint32_t pdb_ms() const;
  void set_pdb_ms(uint32_t value);
  private:
  uint32_t _internal_pdb_ms() const;
  void _internal_set_pdb_ms(uint32_t value);
  public:

  // bool clear_override = 8;
  void clear_clear_override();
  bool clear_override() const;
  void set_clear_override(bool value);
  private:
  bool _internal_clear_override() const;
  void _internal_set_clear_override(bool value);
  public:

  // optional uint64 gbr_ul = 7;
  bool has_gbr_ul() const;
  private:
  bool _internal_has_gbr_ul() const;
  public:
  void clear_gbr_ul();
  uint64_t gbr_ul() const;
  void set_gbr_ul(uint64_t value);
  private:
  uint64_t _internal_gbr_ul() const;
  void _internal_set_gbr_ul(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:DrbQosParams)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t rnti_;
    uint32_t lcid_;
    uint32_t qos_priority_;
    uint32_t arp_priority_;
    uint64_t gbr_dl_;
    uint32_t pdb_ms_;
    bool clear_override_;
    uint64_t gbr_ul_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fqos_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// QosControl

// uint32 ran_index = 1;
inline void QosControl::clear_ran_index() {
  _impl_.ran_index_ = 0u;
}
inline uint32_t QosControl::_internal_ran_index() const {
  return _impl_.ran_index_;
}
inline uint32_t QosControl::ran_index() const {
  // @@protoc_insertion_point(field_get:QosControl.ran_index)
  return _internal_ran_index();
}
inline void QosControl::_internal_set_ran_index(uint32_t value) {
  
  _impl_.ran_index_ = value;
}
inline void QosControl::set_ran_index(uint32_t value) {
  _internal_set_ran_index(value);
  // @@protoc_insertion_point(field_set:QosControl.ran_index)
}

// repeated .DrbQosParams drb_qos = 2;
inline int QosControl::_internal_drb_qos_size() const {
  return _impl_.drb_qos_.size();
}
inline int QosControl::drb_qos_size() const {
  return _internal_drb_qos_size();
}
inline void QosControl::clear_drb_qos() {
  _impl_.drb_qos_.Clear();
}
inline ::DrbQosParams* QosControl::mutable_drb_qos(int index) {
  // @@protoc_insertion_point(field_mutable:QosControl.drb_qos)
  return _impl_.drb_qos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbQosParams >*
QosControl::mutable_drb_qos() {
  // @@protoc_insertion_point(field_mutable_list:QosControl.drb_qos)
  return &_impl_.drb_qos_;
}
inline const ::DrbQosParams& QosControl::_internal_drb_qos(int index) const {
  return _impl_.drb_qos_.Get(index);
}
inline const ::DrbQosParams& QosControl::drb_qos(int index) const {
  // @@protoc_insertion_point(field_get:QosControl.drb_qos)
  return _internal_drb_qos(index);
}
inline ::DrbQosParams* QosControl::_internal_add_drb_qos() {
  return _impl_.drb_qos_.Add();
}
inline ::DrbQosParams* QosControl::add_drb_qos() {
  ::DrbQosParams* _add = _internal_add_drb_qos();
  // @@protoc_insertion_point(field_add:QosControl.drb_qos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbQosParams >&
QosControl::drb_qos() const {
  // @@protoc_insertion_point(field_list:QosControl.drb_qos)
  return _impl_.drb_qos_;
}

// -------------------------------------------------------------------

// DrbQosParams

// uint32 rnti = 1;
inline void DrbQosParams::clear_rnti() {
  _impl_.rnti_ = 0u;
}
inline uint32_t DrbQosParams::_internal_rnti() const {
  return _impl_.rnti_;
}
inline uint32_t DrbQosParams::rnti() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.rnti)
  return _internal_rnti();
}
inline void DrbQosParams::_internal_set_rnti(uint32_t value) {
  
  _impl_.rnti_ = value;
}
inline void DrbQosParams::set_rnti(uint32_t value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.rnti)
}

// uint32 lcid = 2;
inline void DrbQosParams::clear_lcid() {
  _impl_.lcid_ = 0u;
}
inline uint32_t DrbQosParams::_internal_lcid() const {
  return _impl_.lcid_;
}
inline uint32_t DrbQosParams::lcid() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.lcid)
  return _internal_lcid();
}
inline void DrbQosParams::_internal_set_lcid(uint32_t value) {
  
  _impl_.lcid_ = value;
}
inline void DrbQosParams::set_lcid(uint32_t value) {
  _internal_set_lcid(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.lcid)
}

// optional uint32 qos_priority = 3;
inline bool DrbQosParams::_internal_has_qos_priority() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DrbQosParams::has_qos_priority() const {
  return _internal_has_qos_priority();
}
inline void DrbQosParams::clear_qos_priority() {
  _impl_.qos_priority_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t DrbQosParams::_internal_qos_priority() const {
  return _impl_.qos_priority_;
}
inline uint32_t DrbQosParams::qos_priority() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.qos_priority)
  return _internal_qos_priority();
}
inline void DrbQosParams::_internal_set_qos_priority(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.qos_priority_ = value;
}
inline void DrbQosParams::set_qos_priority(uint32_t value) {
  _internal_set_qos_priority(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.qos_priority)
}

// optional uint32 arp_priority = 4;
inline bool DrbQosParams::_internal_has_arp_priority() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DrbQosParams::has_arp_priority() const {
  return _internal_has_arp_priority();
}
inline void DrbQosParams::clear_arp_priority() {
  _impl_.arp_priority_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t DrbQosParams::_internal_arp_priority() const {
  return _impl_.arp_priority_;
}
inline uint32_t DrbQosParams::arp_priority() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.arp_priority)
  return _internal_arp_priority();
}
inline void DrbQosParams::_internal_set_arp_priority(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.arp_priority_ = value;
}
inline void DrbQosParams::set_arp_priority(uint32_t value) {
  _internal_set_arp_priority(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.arp_priority)
}

// optional uint32 pdb_ms = 5;
inline bool DrbQosParams::_internal_has_pdb_ms() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool DrbQosParams::has_pdb_ms() const {
  return _internal_has_pdb_ms();
}
inline void DrbQosParams::clear_pdb_ms() {
  _impl_.pdb_ms_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t DrbQosParams::_internal_pdb_ms() const {
  return _impl_.pdb_ms_;
}
inline uint32_t DrbQosParams::pdb_ms() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.pdb_ms)
  return _internal_pdb_ms();
}
inline void DrbQosParams::_internal_set_pdb_ms(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.pdb_ms_ = value;
}
inline void DrbQosParams::set_pdb_ms(uint32_t value) {
  _internal_set_pdb_ms(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.pdb_ms)
}

// optional uint64 gbr_dl = 6;
inline bool DrbQosParams::_internal_has_gbr_dl() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool DrbQosParams::has_gbr_dl() const {
  return _internal_has_gbr_dl();
}
inline void DrbQosParams::clear_gbr_dl() {
  _impl_.gbr_dl_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint64_t DrbQosParams::_internal_gbr_dl() const {
  return _impl_.gbr_dl_;
}
inline uint64_t DrbQosParams::gbr_dl() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.gbr_dl)
  return _internal_gbr_dl();
}
inline void DrbQosParams::_internal_set_gbr_dl(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.gbr_dl_ = value;
}
inline void DrbQosParams::set_gbr_dl(uint64_t value) {
  _internal_set_gbr_dl(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.gbr_dl)
}

// optional uint64 gbr_ul = 7;
inline bool DrbQosParams::_internal_has_gbr_ul() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool DrbQosParams::has_gbr_ul() const {
  return _internal_has_gbr_ul();
}
inline void DrbQosParams::clear_gbr_ul() {
  _impl_.gbr_ul_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline uint64_t DrbQosParams::_internal_gbr_ul() const {
  return _impl_.gbr_ul_;
}
inline uint64_t DrbQosParams::gbr_ul() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.gbr_ul)
  return _internal_gbr_ul();
}
inline void DrbQosParams::_internal_set_gbr_ul(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.gbr_ul_ = value;
}
inline void DrbQosParams::set_gbr_ul(uint64_t value) {
  _internal_set_gbr_ul(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.gbr_ul)
}

// bool clear_override = 8;
inline void DrbQosParams::clear_clear_override() {
  _impl_.clear_override_ = false;
}
inline bool DrbQosParams::_internal_clear_override() const {
  return _impl_.clear_override_;
}
inline bool DrbQosParams::clear_override() const {
  // @@protoc_insertion_point(field_get:DrbQosParams.clear_override)
  return _internal_clear_override();
}
inline void DrbQosParams::_internal_set_clear_override(bool value) {
  
  _impl_.clear_override_ = value;
}
inline void DrbQosParams::set_clear_override(bool value) {
  _internal_set_clear_override(value);
  // @@protoc_insertion_point(field_set:DrbQosParams.clear_override)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_5fqos_2eproto
