// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_metrics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_metrics_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_metrics_2eproto;
class DrbMetrics;
struct DrbMetricsDefaultTypeInternal;
extern DrbMetricsDefaultTypeInternal _DrbMetrics_default_instance_;
class GtpMetrics;
struct GtpMetricsDefaultTypeInternal;
extern GtpMetricsDefaultTypeInternal _GtpMetrics_default_instance_;
class Metrics;
struct MetricsDefaultTypeInternal;
extern MetricsDefaultTypeInternal _Metrics_default_instance_;
class PdcpDrbMetrics;
struct PdcpDrbMetricsDefaultTypeInternal;
extern PdcpDrbMetricsDefaultTypeInternal _PdcpDrbMetrics_default_instance_;
class UeMetrics;
struct UeMetricsDefaultTypeInternal;
extern UeMetricsDefaultTypeInternal _UeMetrics_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DrbMetrics* Arena::CreateMaybeMessage<::DrbMetrics>(Arena*);
template<> ::GtpMetrics* Arena::CreateMaybeMessage<::GtpMetrics>(Arena*);
template<> ::Metrics* Arena::CreateMaybeMessage<::Metrics>(Arena*);
template<> ::PdcpDrbMetrics* Arena::CreateMaybeMessage<::PdcpDrbMetrics>(Arena*);
template<> ::UeMetrics* Arena::CreateMaybeMessage<::UeMetrics>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class DrbMetrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DrbMetrics) */ {
 public:
  inline DrbMetrics() : DrbMetrics(nullptr) {}
  ~DrbMetrics() override;
  explicit PROTOBUF_CONSTEXPR DrbMetrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DrbMetrics(const DrbMetrics& from);
  DrbMetrics(DrbMetrics&& from) noexcept
    : DrbMetrics() {
    *this = ::std::move(from);
  }

  inline DrbMetrics& operator=(const DrbMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline DrbMetrics& operator=(DrbMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DrbMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const DrbMetrics* internal_default_instance() {
    return reinterpret_cast<const DrbMetrics*>(
               &_DrbMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DrbMetrics& a, DrbMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(DrbMetrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DrbMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DrbMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DrbMetrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DrbMetrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DrbMetrics& from) {
    DrbMetrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DrbMetrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DrbMetrics";
  }
  protected:
  explicit DrbMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLcidFieldNumber = 1,
    kDlBufferFieldNumber = 2,
    kUlBufferFieldNumber = 3,
    kTxBytesFieldNumber = 4,
    kRxBytesFieldNumber = 5,
  };
  // uint32 lcid = 1;
  void clear_lcid();
  uint32_t lcid() const;
  void set_lcid(uint32_t value);
  private:
  uint32_t _internal_lcid() const;
  void _internal_set_lcid(uint32_t value);
  public:

  // uint32 dl_buffer = 2;
  void clear_dl_buffer();
  uint32_t dl_buffer() const;
  void set_dl_buffer(uint32_t value);
  private:
  uint32_t _internal_dl_buffer() const;
  void _internal_set_dl_buffer(uint32_t value);
  public:

  // uint32 ul_buffer = 3;
  void clear_ul_buffer();
  uint32_t ul_buffer() const;
  void set_ul_buffer(uint32_t value);
  private:
  uint32_t _internal_ul_buffer() const;
  void _internal_set_ul_buffer(uint32_t value);
  public:

  // float tx_bytes = 4;
  void clear_tx_bytes();
  float tx_bytes() const;
  void set_tx_bytes(float value);
  private:
  float _internal_tx_bytes() const;
  void _internal_set_tx_bytes(float value);
  public:

  // float rx_bytes = 5;
  void clear_rx_bytes();
  float rx_bytes() const;
  void set_rx_bytes(float value);
  private:
  float _internal_rx_bytes() const;
  void _internal_set_rx_bytes(float value);
  public:

  // @@protoc_insertion_point(class_scope:DrbMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t lcid_;
    uint32_t dl_buffer_;
    uint32_t ul_buffer_;
    float tx_bytes_;
    float rx_bytes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class PdcpDrbMetrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PdcpDrbMetrics) */ {
 public:
  inline PdcpDrbMetrics() : PdcpDrbMetrics(nullptr) {}
  ~PdcpDrbMetrics() override;
  explicit PROTOBUF_CONSTEXPR PdcpDrbMetrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PdcpDrbMetrics(const PdcpDrbMetrics& from);
  PdcpDrbMetrics(PdcpDrbMetrics&& from) noexcept
    : PdcpDrbMetrics() {
    *this = ::std::move(from);
  }

  inline PdcpDrbMetrics& operator=(const PdcpDrbMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline PdcpDrbMetrics& operator=(PdcpDrbMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PdcpDrbMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const PdcpDrbMetrics* internal_default_instance() {
    return reinterpret_cast<const PdcpDrbMetrics*>(
               &_PdcpDrbMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PdcpDrbMetrics& a, PdcpDrbMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(PdcpDrbMetrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PdcpDrbMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PdcpDrbMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PdcpDrbMetrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PdcpDrbMetrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PdcpDrbMetrics& from) {
    PdcpDrbMetrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PdcpDrbMetrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PdcpDrbMetrics";
  }
  protected:
  explicit PdcpDrbMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDrbIdFieldNumber = 1,
    kTxPdusFieldNumber = 2,
    kTxPduBytesFieldNumber = 3,
    kTxDroppedSdusFieldNumber = 4,
    kRxPdusFieldNumber = 5,
    kRxPduBytesFieldNumber = 6,
    kRxDroppedPdusFieldNumber = 7,
    kRxDeliveredSdusFieldNumber = 8,
  };
  // uint32 drb_id = 1;
  void clear_drb_id();
  uint32_t drb_id() const;
  void set_drb_id(uint32_t value);
  private:
  uint32_t _internal_drb_id() const;
  void _internal_set_drb_id(uint32_t value);
  public:

  // uint32 tx_pdus = 2;
  void clear_tx_pdus();
  uint32_t tx_pdus() const;
  void set_tx_pdus(uint32_t value);
  private:
  uint32_t _internal_tx_pdus() const;
  void _internal_set_tx_pdus(uint32_t value);
  public:

  // uint32 tx_pdu_bytes = 3;
  void clear_tx_pdu_bytes();
  uint32_t tx_pdu_bytes() const;
  void set_tx_pdu_bytes(uint32_t value);
  private:
  uint32_t _internal_tx_pdu_bytes() const;
  void _internal_set_tx_pdu_bytes(uint32_t value);
  public:

  // uint32 tx_dropped_sdus = 4;
  void clear_tx_dropped_sdus();
  uint32_t tx_dropped_sdus() const;
  void set_tx_dropped_sdus(uint32_t value);
  private:
  uint32_t _internal_tx_dropped_sdus() const;
  void _internal_set_tx_dropped_sdus(uint32_t value);
  public:

  // uint32 rx_pdus = 5;
  void clear_rx_pdus();
  uint32_t rx_pdus() const;
  void set_rx_pdus(uint32_t value);
  private:
  uint32_t _internal_rx_pdus() const;
  void _internal_set_rx_pdus(uint32_t value);
  public:

  // uint32 rx_pdu_bytes = 6;
  void clear_rx_pdu_bytes();
  uint32_t rx_pdu_bytes() const;
  void set_rx_pdu_bytes(uint32_t value);
  private:
  uint32_t _internal_rx_pdu_bytes() const;
  void _internal_set_rx_pdu_bytes(uint32_t value);
  public:

  // uint32 rx_dropped_pdus = 7;
  void clear_rx_dropped_pdus();
  uint32_t rx_dropped_pdus() const;
  void set_rx_dropped_pdus(uint32_t value);
  private:
  uint32_t _internal_rx_dropped_pdus() const;
  void _internal_set_rx_dropped_pdus(uint32_t value);
  public:

  // uint32 rx_delivered_sdus = 8;
  void clear_rx_delivered_sdus();
  uint32_t rx_delivered_sdus() const;
  void set_rx_delivered_sdus(uint32_t value);
  private:
  uint32_t _internal_rx_delivered_sdus() const;
  void _internal_set_rx_delivered_sdus(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PdcpDrbMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t drb_id_;
    uint32_t tx_pdus_;
    uint32_t tx_pdu_bytes_;
    uint32_t tx_dropped_sdus_;
    uint32_t rx_pdus_;
    uint32_t rx_pdu_bytes_;
    uint32_t rx_dropped_pdus_;
    uint32_t rx_delivered_sdus_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class GtpMetrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GtpMetrics) */ {
 public:
  inline GtpMetrics() : GtpMetrics(nullptr) {}
  ~GtpMetrics() override;
  explicit PROTOBUF_CONSTEXPR GtpMetrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GtpMetrics(const GtpMetrics& from);
  GtpMetrics(GtpMetrics&& from) noexcept
    : GtpMetrics() {
    *this = ::std::move(from);
  }

  inline GtpMetrics& operator=(const GtpMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline GtpMetrics& operator=(GtpMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GtpMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const GtpMetrics* internal_default_instance() {
    return reinterpret_cast<const GtpMetrics*>(
               &_GtpMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GtpMetrics& a, GtpMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(GtpMetrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GtpMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GtpMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GtpMetrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GtpMetrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GtpMetrics& from) {
    GtpMetrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GtpMetrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GtpMetrics";
  }
  protected:
  explicit GtpMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDlPktsFieldNumber = 1,
    kDlBytesFieldNumber = 2,
    kUlPktsFieldNumber = 3,
    kUlBytesFieldNumber = 4,
  };
  // uint32 dl_pkts = 1;
  void clear_dl_pkts();
  uint32_t dl_pkts() const;
  void set_dl_pkts(uint32_t value);
  private:
  uint32_t _internal_dl_pkts() const;
  void _internal_set_dl_pkts(uint32_t value);
  public:

  // uint32 dl_bytes = 2;
  void clear_dl_bytes();
  uint32_t dl_bytes() const;
  void set_dl_bytes(uint32_t value);
  private:
  uint32_t _internal_dl_bytes() const;
  void _internal_set_dl_bytes(uint32_t value);
  public:

  // uint32 ul_pkts = 3;
  void clear_ul_pkts();
  uint32_t ul_pkts() const;
  void set_ul_pkts(uint32_t value);
  private:
  uint32_t _internal_ul_pkts() const;
  void _internal_set_ul_pkts(uint32_t value);
  public:

  // uint32 ul_bytes = 4;
  void clear_ul_bytes();
  uint32_t ul_bytes() const;
  void set_ul_bytes(uint32_t value);
  private:
  uint32_t _internal_ul_bytes() const;
  void _internal_set_ul_bytes(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:GtpMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t dl_pkts_;
    uint32_t dl_bytes_;
    uint32_t ul_pkts_;
    uint32_t ul_bytes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class UeMetrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UeMetrics) */ {
 public:
  inline UeMetrics() : UeMetrics(nullptr) {}
  ~UeMetrics() override;
  explicit PROTOBUF_CONSTEXPR UeMetrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UeMetrics(const UeMetrics& from);
  UeMetrics(UeMetrics&& from) noexcept
    : UeMetrics() {
    *this = ::std::move(from);
  }

  inline UeMetrics& operator=(const UeMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline UeMetrics& operator=(UeMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UeMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const UeMetrics* internal_default_instance() {
    return reinterpret_cast<const UeMetrics*>(
               &_UeMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UeMetrics& a, UeMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(UeMetrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UeMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UeMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UeMetrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UeMetrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UeMetrics& from) {
    UeMetrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UeMetrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UeMetrics";
  }
  protected:
  explicit UeMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDrbMetricsFieldNumber = 13,
    kPdcpDrbMetricsFieldNumber = 14,
    kGtpMetricsFieldNumber = 15,
    kRntiFieldNumber = 1,
    kCqiFieldNumber = 2,
    kSnrFieldNumber = 3,
    kTxBytesFieldNumber = 4,
    kRxBytesFieldNumber = 5,
    kDlBufferFieldNumber = 6,
    kUlBufferFieldNumber = 7,
    kDlTbsFieldNumber = 8,
    kDlOkFieldNumber = 9,
    kDlNokFieldNumber = 10,
    kUlOkFieldNumber = 11,
    kUlNokFieldNumber = 12,
  };
  // repeated .DrbMetrics drb_metrics = 13;
  int drb_metrics_size() const;
  private:
  int _internal_drb_metrics_size() const;
  public:
  void clear_drb_metrics();
  ::DrbMetrics* mutable_drb_metrics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbMetrics >*
      mutable_drb_metrics();
  private:
  const ::DrbMetrics& _internal_drb_metrics(int index) const;
  ::DrbMetrics* _internal_add_drb_metrics();
  public:
  const ::DrbMetrics& drb_metrics(int index) const;
  ::DrbMetrics* add_drb_metrics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbMetrics >&
      drb_metrics() const;

  // repeated .PdcpDrbMetrics pdcp_drb_metrics = 14;
  int pdcp_drb_metrics_size() const;
  private:
  int _internal_pdcp_drb_metrics_size() const;
  public:
  void clear_pdcp_drb_metrics();
  ::PdcpDrbMetrics* mutable_pdcp_drb_metrics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PdcpDrbMetrics >*
      mutable_pdcp_drb_metrics();
  private:
  const ::PdcpDrbMetrics& _internal_pdcp_drb_metrics(int index) const;
  ::PdcpDrbMetrics* _internal_add_pdcp_drb_metrics();
  public:
  const ::PdcpDrbMetrics& pdcp_drb_metrics(int index) const;
  ::PdcpDrbMetrics* add_pdcp_drb_metrics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PdcpDrbMetrics >&
      pdcp_drb_metrics() const;

  // .GtpMetrics gtp_metrics = 15;
  bool has_gtp_metrics() const;
  private:
  bool _internal_has_gtp_metrics() const;
  public:
  void clear_gtp_metrics();
  const ::GtpMetrics& gtp_metrics() const;
  PROTOBUF_NODISCARD ::GtpMetrics* release_gtp_metrics();
  ::GtpMetrics* mutable_gtp_metrics();
  void set_allocated_gtp_metrics(::GtpMetrics* gtp_metrics);
  private:
  const ::GtpMetrics& _internal_gtp_metrics() const;
  ::GtpMetrics* _internal_mutable_gtp_metrics();
  public:
  void unsafe_arena_set_allocated_gtp_metrics(
      ::GtpMetrics* gtp_metrics);
  ::GtpMetrics* unsafe_arena_release_gtp_metrics();

  // uint32 rnti = 1;
  void clear_rnti();
  uint32_t rnti() const;
  void set_rnti(uint32_t value);
  private:
  uint32_t _internal_rnti() const;
  void _internal_set_rnti(uint32_t value);
  public:

  // uint32 cqi = 2;
  void clear_cqi();
  uint32_t cqi() const;
  void set_cqi(uint32_t value);
  private:
  uint32_t _internal_cqi() const;
  void _internal_set_cqi(uint32_t value);
  public:

  // float snr = 3;
  void clear_snr();
  float snr() const;
  void set_snr(float value);
  private:
  float _internal_snr() const;
  void _internal_set_snr(float value);
  public:

  // float tx_bytes = 4;
  void clear_tx_bytes();
  float tx_bytes() const;
  void set_tx_bytes(float value);
  private:
  float _internal_tx_bytes() const;
  void _internal_set_tx_bytes(float value);
  public:

  // float rx_bytes = 5;
  void clear_rx_bytes();
  float rx_bytes() const;
  void set_rx_bytes(float value);
  private:
  float _internal_rx_bytes() const;
  void _internal_set_rx_bytes(float value);
  public:

  // uint32 dl_buffer = 6;
  void clear_dl_buffer();
  uint32_t dl_buffer() const;
  void set_dl_buffer(uint32_t value);
  private:
  uint32_t _internal_dl_buffer() const;
  void _internal_set_dl_buffer(uint32_t value);
  public:

  // uint32 ul_buffer = 7;
  void clear_ul_buffer();
  uint32_t ul_buffer() const;
  void set_ul_buffer(uint32_t value);
  private:
  uint32_t _internal_ul_buffer() const;
  void _internal_set_ul_buffer(uint32_t value);
  public:

  // float dl_tbs = 8;
  void clear_dl_tbs();
  float dl_tbs() const;
  void set_dl_tbs(float value);
  private:
  float _internal_dl_tbs() const;
  void _internal_set_dl_tbs(float value);
  public:

  // uint32 dl_ok = 9;
  void clear_dl_ok();
  uint32_t dl_ok() const;
  void set_dl_ok(uint32_t value);
  private:
  uint32_t _internal_dl_ok() const;
  void _internal_set_dl_ok(uint32_t value);
  public:

  // uint32 dl_nok = 10;
  void clear_dl_nok();
  uint32_t dl_nok() const;
  void set_dl_nok(uint32_t value);
  private:
  uint32_t _internal_dl_nok() const;
  void _internal_set_dl_nok(uint32_t value);
  public:

  // uint32 ul_ok = 11;
  void clear_ul_ok();
  uint32_t ul_ok() const;
  void set_ul_ok(uint32_t value);
  private:
  uint32_t _internal_ul_ok() const;
  void _internal_set_ul_ok(uint32_t value);
  public:

  // uint32 ul_nok = 12;
  void clear_ul_nok();
  uint32_t ul_nok() const;
  void set_ul_nok(uint32_t value);
  private:
  uint32_t _internal_ul_nok() const;
  void _internal_set_ul_nok(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:UeMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbMetrics > drb_metrics_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PdcpDrbMetrics > pdcp_drb_metrics_;
    ::GtpMetrics* gtp_metrics_;
    uint32_t rnti_;
    uint32_t cqi_;
    float snr_;
    float tx_bytes_;
    float rx_bytes_;
    uint32_t dl_buffer_;
    uint32_t ul_buffer_;
    float dl_tbs_;
    uint32_t dl_ok_;
    uint32_t dl_nok_;
    uint32_t ul_ok_;
    uint32_t ul_nok_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Metrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Metrics) */ {
 public:
  inline Metrics() : Metrics(nullptr) {}
  ~Metrics() override;
  explicit PROTOBUF_CONSTEXPR Metrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Metrics(const Metrics& from);
  Metrics(Metrics&& from) noexcept
    : Metrics() {
    *this = ::std::move(from);
  }

  inline Metrics& operator=(const Metrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline Metrics& operator=(Metrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Metrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const Metrics* internal_default_instance() {
    return reinterpret_cast<const Metrics*>(
               &_Metrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Metrics& a, Metrics& b) {
    a.Swap(&b);
  }
  inline void Swap(Metrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Metrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Metrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Metrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Metrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Metrics& from) {
    Metrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Metrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Metrics";
  }
  protected:
  explicit Metrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUeMetricsFieldNumber = 2,
    kTtiCntFieldNumber = 1,
  };
  // repeated .UeMetrics ue_metrics = 2;
  int ue_metrics_size() const;
  private:
  int _internal_ue_metrics_size() const;
  public:
  void clear_ue_metrics();
  ::UeMetrics* mutable_ue_metrics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMetrics >*
      mutable_ue_metrics();
  private:
  const ::UeMetrics& _internal_ue_metrics(int index) const;
  ::UeMetrics* _internal_add_ue_metrics();
  public:
  const ::UeMetrics& ue_metrics(int index) const;
  ::UeMetrics* add_ue_metrics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMetrics >&
      ue_metrics() const;

  // uint32 tti_cnt = 1;
  void clear_tti_cnt();
  uint32_t tti_cnt() const;
  void set_tti_cnt(uint32_t value);
  private:
  uint32_t _internal_tti_cnt() const;
  void _internal_set_tti_cnt(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Metrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMetrics > ue_metrics_;
    uint32_t tti_cnt_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DrbMetrics

// uint32 lcid = 1;
inline void DrbMetrics::clear_lcid() {
  _impl_.lcid_ = 0u;
}
inline uint32_t DrbMetrics::_internal_lcid() const {
  return _impl_.lcid_;
}
inline uint32_t DrbMetrics::lcid() const {
  // @@protoc_insertion_point(field_get:DrbMetrics.lcid)
  return _internal_lcid();
}
inline void DrbMetrics::_internal_set_lcid(uint32_t value) {
  
  _impl_.lcid_ = value;
}
inline void DrbMetrics::set_lcid(uint32_t value) {
  _internal_set_lcid(value);
  // @@protoc_insertion_point(field_set:DrbMetrics.lcid)
}

// uint32 dl_buffer = 2;
inline void DrbMetrics::clear_dl_buffer() {
  _impl_.dl_buffer_ = 0u;
}
inline uint32_t DrbMetrics::_internal_dl_buffer() const {
  return _impl_.dl_buffer_;
}
inline uint32_t DrbMetrics::dl_buffer() const {
  // @@protoc_insertion_point(field_get:DrbMetrics.dl_buffer)
  return _internal_dl_buffer();
}
inline void DrbMetrics::_internal_set_dl_buffer(uint32_t value) {
  
  _impl_.dl_buffer_ = value;
}
inline void DrbMetrics::set_dl_buffer(uint32_t value) {
  _internal_set_dl_buffer(value);
  // @@protoc_insertion_point(field_set:DrbMetrics.dl_buffer)
}

// uint32 ul_buffer = 3;
inline void DrbMetrics::clear_ul_buffer() {
  _impl_.ul_buffer_ = 0u;
}
inline uint32_t DrbMetrics::_internal_ul_buffer() const {
  return _impl_.ul_buffer_;
}
inline uint32_t DrbMetrics::ul_buffer() const {
  // @@protoc_insertion_point(field_get:DrbMetrics.ul_buffer)
  return _internal_ul_buffer();
}
inline void DrbMetrics::_internal_set_ul_buffer(uint32_t value) {
  
  _impl_.ul_buffer_ = value;
}
inline void DrbMetrics::set_ul_buffer(uint32_t value) {
  _internal_set_ul_buffer(value);
  // @@protoc_insertion_point(field_set:DrbMetrics.ul_buffer)
}

// float tx_bytes = 4;
inline void DrbMetrics::clear_tx_bytes() {
  _impl_.tx_bytes_ = 0;
}
inline float DrbMetrics::_internal_tx_bytes() const {
  return _impl_.tx_bytes_;
}
inline float DrbMetrics::tx_bytes() const {
  // @@protoc_insertion_point(field_get:DrbMetrics.tx_bytes)
  return _internal_tx_bytes();
}
inline void DrbMetrics::_internal_set_tx_bytes(float value) {
  
  _impl_.tx_bytes_ = value;
}
inline void DrbMetrics::set_tx_bytes(float value) {
  _internal_set_tx_bytes(value);
  // @@protoc_insertion_point(field_set:DrbMetrics.tx_bytes)
}

// float rx_bytes = 5;
inline void DrbMetrics::clear_rx_bytes() {
  _impl_.rx_bytes_ = 0;
}
inline float DrbMetrics::_internal_rx_bytes() const {
  return _impl_.rx_bytes_;
}
inline float DrbMetrics::rx_bytes() const {
  // @@protoc_insertion_point(field_get:DrbMetrics.rx_bytes)
  return _internal_rx_bytes();
}
inline void DrbMetrics::_internal_set_rx_bytes(float value) {
  
  _impl_.rx_bytes_ = value;
}
inline void DrbMetrics::set_rx_bytes(float value) {
  _internal_set_rx_bytes(value);
  // @@protoc_insertion_point(field_set:DrbMetrics.rx_bytes)
}

// -------------------------------------------------------------------

// PdcpDrbMetrics

// uint32 drb_id = 1;
inline void PdcpDrbMetrics::clear_drb_id() {
  _impl_.drb_id_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_drb_id() const {
  return _impl_.drb_id_;
}
inline uint32_t PdcpDrbMetrics::drb_id() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.drb_id)
  return _internal_drb_id();
}
inline void PdcpDrbMetrics::_internal_set_drb_id(uint32_t value) {
  
  _impl_.drb_id_ = value;
}
inline void PdcpDrbMetrics::set_drb_id(uint32_t value) {
  _internal_set_drb_id(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.drb_id)
}

// uint32 tx_pdus = 2;
inline void PdcpDrbMetrics::clear_tx_pdus() {
  _impl_.tx_pdus_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_tx_pdus() const {
  return _impl_.tx_pdus_;
}
inline uint32_t PdcpDrbMetrics::tx_pdus() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.tx_pdus)
  return _internal_tx_pdus();
}
inline void PdcpDrbMetrics::_internal_set_tx_pdus(uint32_t value) {
  
  _impl_.tx_pdus_ = value;
}
inline void PdcpDrbMetrics::set_tx_pdus(uint32_t value) {
  _internal_set_tx_pdus(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.tx_pdus)
}

// uint32 tx_pdu_bytes = 3;
inline void PdcpDrbMetrics::clear_tx_pdu_bytes() {
  _impl_.tx_pdu_bytes_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_tx_pdu_bytes() const {
  return _impl_.tx_pdu_bytes_;
}
inline uint32_t PdcpDrbMetrics::tx_pdu_bytes() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.tx_pdu_bytes)
  return _internal_tx_pdu_bytes();
}
inline void PdcpDrbMetrics::_internal_set_tx_pdu_bytes(uint32_t value) {
  
  _impl_.tx_pdu_bytes_ = value;
}
inline void PdcpDrbMetrics::set_tx_pdu_bytes(uint32_t value) {
  _internal_set_tx_pdu_bytes(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.tx_pdu_bytes)
}

// uint32 tx_dropped_sdus = 4;
inline void PdcpDrbMetrics::clear_tx_dropped_sdus() {
  _impl_.tx_dropped_sdus_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_tx_dropped_sdus() const {
  return _impl_.tx_dropped_sdus_;
}
inline uint32_t PdcpDrbMetrics::tx_dropped_sdus() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.tx_dropped_sdus)
  return _internal_tx_dropped_sdus();
}
inline void PdcpDrbMetrics::_internal_set_tx_dropped_sdus(uint32_t value) {
  
  _impl_.tx_dropped_sdus_ = value;
}
inline void PdcpDrbMetrics::set_tx_dropped_sdus(uint32_t value) {
  _internal_set_tx_dropped_sdus(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.tx_dropped_sdus)
}

// uint32 rx_pdus = 5;
inline void PdcpDrbMetrics::clear_rx_pdus() {
  _impl_.rx_pdus_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_rx_pdus() const {
  return _impl_.rx_pdus_;
}
inline uint32_t PdcpDrbMetrics::rx_pdus() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.rx_pdus)
  return _internal_rx_pdus();
}
inline void PdcpDrbMetrics::_internal_set_rx_pdus(uint32_t value) {
  
  _impl_.rx_pdus_ = value;
}
inline void PdcpDrbMetrics::set_rx_pdus(uint32_t value) {
  _internal_set_rx_pdus(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.rx_pdus)
}

// uint32 rx_pdu_bytes = 6;
inline void PdcpDrbMetrics::clear_rx_pdu_bytes() {
  _impl_.rx_pdu_bytes_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_rx_pdu_bytes() const {
  return _impl_.rx_pdu_bytes_;
}
inline uint32_t PdcpDrbMetrics::rx_pdu_bytes() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.rx_pdu_bytes)
  return _internal_rx_pdu_bytes();
}
inline void PdcpDrbMetrics::_internal_set_rx_pdu_bytes(uint32_t value) {
  
  _impl_.rx_pdu_bytes_ = value;
}
inline void PdcpDrbMetrics::set_rx_pdu_bytes(uint32_t value) {
  _internal_set_rx_pdu_bytes(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.rx_pdu_bytes)
}

// uint32 rx_dropped_pdus = 7;
inline void PdcpDrbMetrics::clear_rx_dropped_pdus() {
  _impl_.rx_dropped_pdus_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_rx_dropped_pdus() const {
  return _impl_.rx_dropped_pdus_;
}
inline uint32_t PdcpDrbMetrics::rx_dropped_pdus() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.rx_dropped_pdus)
  return _internal_rx_dropped_pdus();
}
inline void PdcpDrbMetrics::_internal_set_rx_dropped_pdus(uint32_t value) {
  
  _impl_.rx_dropped_pdus_ = value;
}
inline void PdcpDrbMetrics::set_rx_dropped_pdus(uint32_t value) {
  _internal_set_rx_dropped_pdus(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.rx_dropped_pdus)
}

// uint32 rx_delivered_sdus = 8;
inline void PdcpDrbMetrics::clear_rx_delivered_sdus() {
  _impl_.rx_delivered_sdus_ = 0u;
}
inline uint32_t PdcpDrbMetrics::_internal_rx_delivered_sdus() const {
  return _impl_.rx_delivered_sdus_;
}
inline uint32_t PdcpDrbMetrics::rx_delivered_sdus() const {
  // @@protoc_insertion_point(field_get:PdcpDrbMetrics.rx_delivered_sdus)
  return _internal_rx_delivered_sdus();
}
inline void PdcpDrbMetrics::_internal_set_rx_delivered_sdus(uint32_t value) {
  
  _impl_.rx_delivered_sdus_ = value;
}
inline void PdcpDrbMetrics::set_rx_delivered_sdus(uint32_t value) {
  _internal_set_rx_delivered_sdus(value);
  // @@protoc_insertion_point(field_set:PdcpDrbMetrics.rx_delivered_sdus)
}

// -------------------------------------------------------------------

// GtpMetrics

// uint32 dl_pkts = 1;
inline void GtpMetrics::clear_dl_pkts() {
  _impl_.dl_pkts_ = 0u;
}
inline uint32_t GtpMetrics::_internal_dl_pkts() const {
  return _impl_.dl_pkts_;
}
inline uint32_t GtpMetrics::dl_pkts() const {
  // @@protoc_insertion_point(field_get:GtpMetrics.dl_pkts)
  return _internal_dl_pkts();
}
inline void GtpMetrics::_internal_set_dl_pkts(uint32_t value) {
  
  _impl_.dl_pkts_ = value;
}
inline void GtpMetrics::set_dl_pkts(uint32_t value) {
  _internal_set_dl_pkts(value);
  // @@protoc_insertion_point(field_set:GtpMetrics.dl_pkts)
}

// uint32 dl_bytes = 2;
inline void GtpMetrics::clear_dl_bytes() {
  _impl_.dl_bytes_ = 0u;
}
inline uint32_t GtpMetrics::_internal_dl_bytes() const {
  return _impl_.dl_bytes_;
}
inline uint32_t GtpMetrics::dl_bytes() const {
  // @@protoc_insertion_point(field_get:GtpMetrics.dl_bytes)
  return _internal_dl_bytes();
}
inline void GtpMetrics::_internal_set_dl_bytes(uint32_t value) {
  
  _impl_.dl_bytes_ = value;
}
inline void GtpMetrics::set_dl_bytes(uint32_t value) {
  _internal_set_dl_bytes(value);
  // @@protoc_insertion_point(field_set:GtpMetrics.dl_bytes)
}

// uint32 ul_pkts = 3;
inline void GtpMetrics::clear_ul_pkts() {
  _impl_.ul_pkts_ = 0u;
}
inline uint32_t GtpMetrics::_internal_ul_pkts() const {
  return _impl_.ul_pkts_;
}
inline uint32_t GtpMetrics::ul_pkts() const {
  // @@protoc_insertion_point(field_get:GtpMetrics.ul_pkts)
  return _internal_ul_pkts();
}
inline void GtpMetrics::_internal_set_ul_pkts(uint32_t value) {
  
  _impl_.ul_pkts_ = value;
}
inline void GtpMetrics::set_ul_pkts(uint32_t value) {
  _internal_set_ul_pkts(value);
  // @@protoc_insertion_point(field_set:GtpMetrics.ul_pkts)
}

// uint32 ul_bytes = 4;
inline void GtpMetrics::clear_ul_bytes() {
  _impl_.ul_bytes_ = 0u;
}
inline uint32_t GtpMetrics::_internal_ul_bytes() const {
  return _impl_.ul_bytes_;
}
inline uint32_t GtpMetrics::ul_bytes() const {
  // @@protoc_insertion_point(field_get:GtpMetrics.ul_bytes)
  return _internal_ul_bytes();
}
inline void GtpMetrics::_internal_set_ul_bytes(uint32_t value) {
  
  _impl_.ul_bytes_ = value;
}
inline void GtpMetrics::set_ul_bytes(uint32_t value) {
  _internal_set_ul_bytes(value);
  // @@protoc_insertion_point(field_set:GtpMetrics.ul_bytes)
}

// -------------------------------------------------------------------

// UeMetrics

// uint32 rnti = 1;
inline void UeMetrics::clear_rnti() {
  _impl_.rnti_ = 0u;
}
inline uint32_t UeMetrics::_internal_rnti() const {
  return _impl_.rnti_;
}
inline uint32_t UeMetrics::rnti() const {
  // @@protoc_insertion_point(field_get:UeMetrics.rnti)
  return _internal_rnti();
}
inline void UeMetrics::_internal_set_rnti(uint32_t value) {
  
  _impl_.rnti_ = value;
}
inline void UeMetrics::set_rnti(uint32_t value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:UeMetrics.rnti)
}

// uint32 cqi = 2;
inline void UeMetrics::clear_cqi() {
  _impl_.cqi_ = 0u;
}
inline uint32_t UeMetrics::_internal_cqi() const {
  return _impl_.cqi_;
}
inline uint32_t UeMetrics::cqi() const {
  // @@protoc_insertion_point(field_get:UeMetrics.cqi)
  return _internal_cqi();
}
inline void UeMetrics::_internal_set_cqi(uint32_t value) {
  
  _impl_.cqi_ = value;
}
inline void UeMetrics::set_cqi(uint32_t value) {
  _internal_set_cqi(value);
  // @@protoc_insertion_point(field_set:UeMetrics.cqi)
}

// float snr = 3;
inline void UeMetrics::clear_snr() {
  _impl_.snr_ = 0;
}
inline float UeMetrics::_internal_snr() const {
  return _impl_.snr_;
}
inline float UeMetrics::snr() const {
  // @@protoc_insertion_point(field_get:UeMetrics.snr)
  return _internal_snr();
}
inline void UeMetrics::_internal_set_snr(float value) {
  
  _impl_.snr_ = value;
}
inline void UeMetrics::set_snr(float value) {
  _internal_set_snr(value);
  // @@protoc_insertion_point(field_set:UeMetrics.snr)
}

// float tx_bytes = 4;
inline void UeMetrics::clear_tx_bytes() {
  _impl_.tx_bytes_ = 0;
}
inline float UeMetrics::_internal_tx_bytes() const {
  return _impl_.tx_bytes_;
}
inline float UeMetrics::tx_bytes() const {
  // @@protoc_insertion_point(field_get:UeMetrics.tx_bytes)
  return _internal_tx_bytes();
}
inline void UeMetrics::_internal_set_tx_bytes(float value) {
  
  _impl_.tx_bytes_ = value;
}
inline void UeMetrics::set_tx_bytes(float value) {
  _internal_set_tx_bytes(value);
  // @@protoc_insertion_point(field_set:UeMetrics.tx_bytes)
}

// float rx_bytes = 5;
inline void UeMetrics::clear_rx_bytes() {
  _impl_.rx_bytes_ = 0;
}
inline float UeMetrics::_internal_rx_bytes() const {
  return _impl_.rx_bytes_;
}
inline float UeMetrics::rx_bytes() const {
  // @@protoc_insertion_point(field_get:UeMetrics.rx_bytes)
  return _internal_rx_bytes();
}
inline void UeMetrics::_internal_set_rx_bytes(float value) {
  
  _impl_.rx_bytes_ = value;
}
inline void UeMetrics::set_rx_bytes(float value) {
  _internal_set_rx_bytes(value);
  // @@protoc_insertion_point(field_set:UeMetrics.rx_bytes)
}

// uint32 dl_buffer = 6;
inline void UeMetrics::clear_dl_buffer() {
  _impl_.dl_buffer_ = 0u;
}
inline uint32_t UeMetrics::_internal_dl_buffer() const {
  return _impl_.dl_buffer_;
}
inline uint32_t UeMetrics::dl_buffer() const {
  // @@protoc_insertion_point(field_get:UeMetrics.dl_buffer)
  return _internal_dl_buffer();
}
inline void UeMetrics::_internal_set_dl_buffer(uint32_t value) {
  
  _impl_.dl_buffer_ = value;
}
inline void UeMetrics::set_dl_buffer(uint32_t value) {
  _internal_set_dl_buffer(value);
  // @@protoc_insertion_point(field_set:UeMetrics.dl_buffer)
}

// uint32 ul_buffer = 7;
inline void UeMetrics::clear_ul_buffer() {
  _impl_.ul_buffer_ = 0u;
}
inline uint32_t UeMetrics::_internal_ul_buffer() const {
  return _impl_.ul_buffer_;
}
inline uint32_t UeMetrics::ul_buffer() const {
  // @@protoc_insertion_point(field_get:UeMetrics.ul_buffer)
  return _internal_ul_buffer();
}
inline void UeMetrics::_internal_set_ul_buffer(uint32_t value) {
  
  _impl_.ul_buffer_ = value;
}
inline void UeMetrics::set_ul_buffer(uint32_t value) {
  _internal_set_ul_buffer(value);
  // @@protoc_insertion_point(field_set:UeMetrics.ul_buffer)
}

// float dl_tbs = 8;
inline void UeMetrics::clear_dl_tbs() {
  _impl_.dl_tbs_ = 0;
}
inline float UeMetrics::_internal_dl_tbs() const {
  return _impl_.dl_tbs_;
}
inline float UeMetrics::dl_tbs() const {
  // @@protoc_insertion_point(field_get:UeMetrics.dl_tbs)
  return _internal_dl_tbs();
}
inline void UeMetrics::_internal_set_dl_tbs(float value) {
  
  _impl_.dl_tbs_ = value;
}
inline void UeMetrics::set_dl_tbs(float value) {
  _internal_set_dl_tbs(value);
  // @@protoc_insertion_point(field_set:UeMetrics.dl_tbs)
}

// uint32 dl_ok = 9;
inline void UeMetrics::clear_dl_ok() {
  _impl_.dl_ok_ = 0u;
}
inline uint32_t UeMetrics::_internal_dl_ok() const {
  return _impl_.dl_ok_;
}
inline uint32_t UeMetrics::dl_ok() const {
  // @@protoc_insertion_point(field_get:UeMetrics.dl_ok)
  return _internal_dl_ok();
}
inline void UeMetrics::_internal_set_dl_ok(uint32_t value) {
  
  _impl_.dl_ok_ = value;
}
inline void UeMetrics::set_dl_ok(uint32_t value) {
  _internal_set_dl_ok(value);
  // @@protoc_insertion_point(field_set:UeMetrics.dl_ok)
}

// uint32 dl_nok = 10;
inline void UeMetrics::clear_dl_nok() {
  _impl_.dl_nok_ = 0u;
}
inline uint32_t UeMetrics::_internal_dl_nok() const {
  return _impl_.dl_nok_;
}
inline uint32_t UeMetrics::dl_nok() const {
  // @@protoc_insertion_point(field_get:UeMetrics.dl_nok)
  return _internal_dl_nok();
}
inline void UeMetrics::_internal_set_dl_nok(uint32_t value) {
  
  _impl_.dl_nok_ = value;
}
inline void UeMetrics::set_dl_nok(uint32_t value) {
  _internal_set_dl_nok(value);
  // @@protoc_insertion_point(field_set:UeMetrics.dl_nok)
}

// uint32 ul_ok = 11;
inline void UeMetrics::clear_ul_ok() {
  _impl_.ul_ok_ = 0u;
}
inline uint32_t UeMetrics::_internal_ul_ok() const {
  return _impl_.ul_ok_;
}
inline uint32_t UeMetrics::ul_ok() const {
  // @@protoc_insertion_point(field_get:UeMetrics.ul_ok)
  return _internal_ul_ok();
}
inline void UeMetrics::_internal_set_ul_ok(uint32_t value) {
  
  _impl_.ul_ok_ = value;
}
inline void UeMetrics::set_ul_ok(uint32_t value) {
  _internal_set_ul_ok(value);
  // @@protoc_insertion_point(field_set:UeMetrics.ul_ok)
}

// uint32 ul_nok = 12;
inline void UeMetrics::clear_ul_nok() {
  _impl_.ul_nok_ = 0u;
}
inline uint32_t UeMetrics::_internal_ul_nok() const {
  return _impl_.ul_nok_;
}
inline uint32_t UeMetrics::ul_nok() const {
  // @@protoc_insertion_point(field_get:UeMetrics.ul_nok)
  return _internal_ul_nok();
}
inline void UeMetrics::_internal_set_ul_nok(uint32_t value) {
  
  _impl_.ul_nok_ = value;
}
inline void UeMetrics::set_ul_nok(uint32_t value) {
  _internal_set_ul_nok(value);
  // @@protoc_insertion_point(field_set:UeMetrics.ul_nok)
}

// repeated .DrbMetrics drb_metrics = 13;
inline int UeMetrics::_internal_drb_metrics_size() const {
  return _impl_.drb_metrics_.size();
}
inline int UeMetrics::drb_metrics_size() const {
  return _internal_drb_metrics_size();
}
inline void UeMetrics::clear_drb_metrics() {
  _impl_.drb_metrics_.Clear();
}
inline ::DrbMetrics* UeMetrics::mutable_drb_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:UeMetrics.drb_metrics)
  return _impl_.drb_metrics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbMetrics >*
UeMetrics::mutable_drb_metrics() {
  // @@protoc_insertion_point(field_mutable_list:UeMetrics.drb_metrics)
  return &_impl_.drb_metrics_;
}
inline const ::DrbMetrics& UeMetrics::_internal_drb_metrics(int index) const {
  return _impl_.drb_metrics_.Get(index);
}
inline const ::DrbMetrics& UeMetrics::drb_metrics(int index) const {
  // @@protoc_insertion_point(field_get:UeMetrics.drb_metrics)
  return _internal_drb_metrics(index);
}
inline ::DrbMetrics* UeMetrics::_internal_add_drb_metrics() {
  return _impl_.drb_metrics_.Add();
}
inline ::DrbMetrics* UeMetrics::add_drb_metrics() {
  ::DrbMetrics* _add = _internal_add_drb_metrics();
  // @@protoc_insertion_point(field_add:UeMetrics.drb_metrics)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DrbMetrics >&
UeMetrics::drb_metrics() const {
  // @@protoc_insertion_point(field_list:UeMetrics.drb_metrics)
  return _impl_.drb_metrics_;
}

// repeated .PdcpDrbMetrics pdcp_drb_metrics = 14;
inline int UeMetrics::_internal_pdcp_drb_metrics_size() const {
  return _impl_.pdcp_drb_metrics_.size();
}
inline int UeMetrics::pdcp_drb_metrics_size() const {
  return _internal_pdcp_drb_metrics_size();
}
inline void UeMetrics::clear_pdcp_drb_metrics() {
  _impl_.pdcp_drb_metrics_.Clear();
}
inline ::PdcpDrbMetrics* UeMetrics::mutable_pdcp_drb_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:UeMetrics.pdcp_drb_metrics)
  return _impl_.pdcp_drb_metrics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PdcpDrbMetrics >*
UeMetrics::mutable_pdcp_drb_metrics() {
  // @@protoc_insertion_point(field_mutable_list:UeMetrics.pdcp_drb_metrics)
  return &_impl_.pdcp_drb_metrics_;
}
inline const ::PdcpDrbMetrics& UeMetrics::_internal_pdcp_drb_metrics(int index) const {
  return _impl_.pdcp_drb_metrics_.Get(index);
}
inline const ::PdcpDrbMetrics& UeMetrics::pdcp_drb_metrics(int index) const {
  // @@protoc_insertion_point(field_get:UeMetrics.pdcp_drb_metrics)
  return _internal_pdcp_drb_metrics(index);
}
inline ::PdcpDrbMetrics* UeMetrics::_internal_add_pdcp_drb_metrics() {
  return _impl_.pdcp_drb_metrics_.Add();
}
inline ::PdcpDrbMetrics* UeMetrics::add_pdcp_drb_metrics() {
  ::PdcpDrbMetrics* _add = _internal_add_pdcp_drb_metrics();
  // @@protoc_insertion_point(field_add:UeMetrics.pdcp_drb_metrics)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PdcpDrbMetrics >&
UeMetrics::pdcp_drb_metrics() const {
  // @@protoc_insertion_point(field_list:UeMetrics.pdcp_drb_metrics)
  return _impl_.pdcp_drb_metrics_;
}

// .GtpMetrics gtp_metrics = 15;
inline bool UeMetrics::_internal_has_gtp_metrics() const {
  return this != internal_default_instance() && _impl_.gtp_metrics_ != nullptr;
}
inline bool UeMetrics::has_gtp_metrics() const {
  return _internal_has_gtp_metrics();
}
inline void UeMetrics::clear_gtp_metrics() {
  if (GetArenaForAllocation() == nullptr && _impl_.gtp_metrics_ != nullptr) {
    delete _impl_.gtp_metrics_;
  }
  _impl_.gtp_metrics_ = nullptr;
}
inline const ::GtpMetrics& UeMetrics::_internal_gtp_metrics() const {
  const ::GtpMetrics* p = _impl_.gtp_metrics_;
  return p != nullptr ? *p : reinterpret_cast<const ::GtpMetrics&>(
      ::_GtpMetrics_default_instance_);
}
inline const ::GtpMetrics& UeMetrics::gtp_metrics() const {
  // @@protoc_insertion_point(field_get:UeMetrics.gtp_metrics)
  return _internal_gtp_metrics();
}
inline void UeMetrics::unsafe_arena_set_allocated_gtp_metrics(
    ::GtpMetrics* gtp_metrics) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.gtp_metrics_);
  }
  _impl_.gtp_metrics_ = gtp_metrics;
  if (gtp_metrics) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:UeMetrics.gtp_metrics)
}
inline ::GtpMetrics* UeMetrics::release_gtp_metrics() {
  
  ::GtpMetrics* temp = _impl_.gtp_metrics_;
  _impl_.gtp_metrics_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GtpMetrics* UeMetrics::unsafe_arena_release_gtp_metrics() {
  // @@protoc_insertion_point(field_release:UeMetrics.gtp_metrics)
  
  ::GtpMetrics* temp = _impl_.gtp_metrics_;
  _impl_.gtp_metrics_ = nullptr;
  return temp;
}
inline ::GtpMetrics* UeMetrics::_internal_mutable_gtp_metrics() {
  
  if (_impl_.gtp_metrics_ == nullptr) {
    auto* p = CreateMaybeMessage<::GtpMetrics>(GetArenaForAllocation());
    _impl_.gtp_metrics_ = p;
  }
  return _impl_.gtp_metrics_;
}
inline ::GtpMetrics* UeMetrics::mutable_gtp_metrics() {
  ::GtpMetrics* _msg = _internal_mutable_gtp_metrics();
  // @@protoc_insertion_point(field_mutable:UeMetrics.gtp_metrics)
  return _msg;
}
inline void UeMetrics::set_allocated_gtp_metrics(::GtpMetrics* gtp_metrics) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.gtp_metrics_;
  }
  if (gtp_metrics) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(gtp_metrics);
    if (message_arena != submessage_arena) {
      gtp_metrics = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gtp_metrics, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.gtp_metrics_ = gtp_metrics;
  // @@protoc_insertion_point(field_set_allocated:UeMetrics.gtp_metrics)
}

// -------------------------------------------------------------------

// Metrics

// uint32 tti_cnt = 1;
inline void Metrics::clear_tti_cnt() {
  _impl_.tti_cnt_ = 0u;
}
inline uint32_t Metrics::_internal_tti_cnt() const {
  return _impl_.tti_cnt_;
}
inline uint32_t Metrics::tti_cnt() const {
  // @@protoc_insertion_point(field_get:Metrics.tti_cnt)
  return _internal_tti_cnt();
}
inline void Metrics::_internal_set_tti_cnt(uint32_t value) {
  
  _impl_.tti_cnt_ = value;
}
inline void Metrics::set_tti_cnt(uint32_t value) {
  _internal_set_tti_cnt(value);
  // @@protoc_insertion_point(field_set:Metrics.tti_cnt)
}

// repeated .UeMetrics ue_metrics = 2;
inline int Metrics::_internal_ue_metrics_size() const {
  return _impl_.ue_metrics_.size();
}
inline int Metrics::ue_metrics_size() const {
  return _internal_ue_metrics_size();
}
inline void Metrics::clear_ue_metrics() {
  _impl_.ue_metrics_.Clear();
}
inline ::UeMetrics* Metrics::mutable_ue_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:Metrics.ue_metrics)
  return _impl_.ue_metrics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMetrics >*
Metrics::mutable_ue_metrics() {
  // @@protoc_insertion_point(field_mutable_list:Metrics.ue_metrics)
  return &_impl_.ue_metrics_;
}
inline const ::UeMetrics& Metrics::_internal_ue_metrics(int index) const {
  return _impl_.ue_metrics_.Get(index);
}
inline const ::UeMetrics& Metrics::ue_metrics(int index) const {
  // @@protoc_insertion_point(field_get:Metrics.ue_metrics)
  return _internal_ue_metrics(index);
}
inline ::UeMetrics* Metrics::_internal_add_ue_metrics() {
  return _impl_.ue_metrics_.Add();
}
inline ::UeMetrics* Metrics::add_ue_metrics() {
  ::UeMetrics* _add = _internal_add_ue_metrics();
  // @@protoc_insertion_point(field_add:Metrics.ue_metrics)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMetrics >&
Metrics::ue_metrics() const {
  // @@protoc_insertion_point(field_list:Metrics.ue_metrics)
  return _impl_.ue_metrics_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto
