# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_qos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ontrol_qos.proto\"?\n\nQosControl\x12\x11\n\tran_index\x18\x01 \x01(\r\x12\x1e\n\x07\x64rb_qos\x18\x02 \x03(\x0b\x32\r.DrbQosParams\"\xfa\x01\n\x0c\x44rbQosParams\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x0c\n\x04lcid\x18\x02 \x01(\r\x12\x19\n\x0cqos_priority\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0c\x61rp_priority\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x13\n\x06pdb_ms\x18\x05 \x01(\rH\x02\x88\x01\x01\x12\x13\n\x06gbr_dl\x18\x06 \x01(\x04H\x03\x88\x01\x01\x12\x13\n\x06gbr_ul\x18\x07 \x01(\x04H\x04\x88\x01\x01\x12\x16\n\x0e\x63lear_override\x18\x08 \x01(\x08\x42\x0f\n\r_qos_priorityB\x0f\n\r_arp_priorityB\t\n\x07_pdb_msB\t\n\x07_gbr_dlB\t\n\x07_gbr_ulb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_qos_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QOSCONTROL._serialized_start=21
  _QOSCONTROL._serialized_end=84
  _DRBQOSPARAMS._serialized_start=87
  _DRBQOSPARAMS._serialized_end=337
# @@protoc_insertion_point(module_scope)
